export const header = [
    {
        id: 1,
        title: "Asosiy",
        link: "/",
        icon: "bx bxs-dashboard",
        role: "_sp_am_, _ow_sch_, _ad_sch_",
    },
    {
        id: 2,
        title: "Mijozlar",
        link: "/customer",
        icon: "bx bx-body",
        role: '_sp_am_, _ad_sch_',
    },
    {
        id: 3,
        title: "Xodimlar",
        link: "/employees",
        icon: "bx bxs-user-rectangle",
        role: '_sp_am_, _ow_sch_, _ad_sch_',
    },
    {
        id: 4,
        title: "O'quvchilar",
        link: "/students",
        icon: "bx bxs-user",
        role: '_sp_am_, _ad_sch_',
    },
    {
        id: 5,
        title: "Guruhlar",
        link: "/groups",
        icon: "bx bxs-group",
        role: '_sp_am_, _ad_sch_',
    },
    {
        id: 6,
        title: "Fanlar",
        link: "/subjects",
        icon: "bx bxs-book-bookmark",
        role: '_sp_am_, _ad_sch_',
    },
    {
        id: 7,
        title: "Davomat",
        link: "/attendance",
        icon: "bx bx-user-check",
        role: '_sp_am_, _ad_sch_',
    },
    // {
    //     id: 8,
    //     title: "Testlar",
    //     link: "/tests",
    //     icon: "bx bx-credit-card-front",
    //     role: '_sp_am_, _ad_sch_',
    // },
    // {
    //     id: 9,
    //     title: "Natijalar",
    //     link: "/results",
    //     icon: "bx bxs-pie-chart-alt-2",
    //     role: '_sp_am_, _ad_sch_',
    // },
    {
        id: 8,
        title: "To'lovlar",
        link: "/payment",
        icon: "bx bxs-credit-card",
        role: '_sp_am_, _ad_sch_',
    },
    {
        id: 9,
        title: "Sms",
        link: "/sms",
        icon: "bx bxs-message-rounded-dots",
        role: '_sp_am_, _ad_sch_',
    },
    {
        id: 10,
        title: "Sozlamalar",
        link: "/settings",
        icon: "bx bxs-cog",
        role: '_sp_am_, _ow_sch_, _ad_sch_',
    },
];
